spring:
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:52520/railway
    username: postgres
    password: nIfRyFjVYXGcPvJjRZFyezVVPuldprcQ
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate